CREATE TABLE DEPARTMENTS(
    DEPT_NO CHAR(4) PRIMARY KEY,
    DEPT_NAME VARCHAR(40) NOT NULL
);

CREATE TABLE EMPLOYEES(
    EMP_NO INT(11) PRIMARY KEY,
    BIRTH_DATE DATE NOT NULL,
    FIRST_NAME VARCHAR(14) NOT NULL,
    LAST_NAME VARCHAR(16) NOT NULL,
    GENDER ENUM('M','F') NOT NULL,
    HIRE_DATE DATE NOT NULL
);

CREATE TABLE DEPT_EMP(
    EMP_NO INT(11),
    DEPT_NO CHAR(4),
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE,
    INDEX(EMP_NO),
    CONSTRAINT FK_EMP_NO FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
    INDEX(DEPT_NO),
    CONSTRAINT FK_DEPT_NO FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO),
    CONSTRAINT PK_DEPT_EMP PRIMARY KEY(EMP_NO, DEPT_NO)
);

CREATE TABLE DEPT_MANAGER(
    DEPT_NO CHAR(4),
    EMP_NO INT(11),
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE,
    INDEX(DEPT_NO),
    CONSTRAINT FK_DEPT_MANAGER_NO FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO),
    INDEX(EMP_NO),
    CONSTRAINT FK_EMP_MANAGER_NO FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
    CONSTRAINT PK_DEPT_MANAGER PRIMARY KEY(EMP_NO, DEPT_NO)
);

CREATE TABLE SALARIES(
    EMP_NO INT(11),
    SALARY INT(11),
    FROM_DATE DATE,
    TO_DATE DATE,
    INDEX(EMP_NO),
    CONSTRAINT FK_EMP_SALARY FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
    CONSTRAINT PK_SALARY PRIMARY KEY(EMP_NO, FROM_DATE)
);

CREATE TABLE TITLES(
    EMP_NO INT(11),
    TITLE VARCHAR(50),
    FROM_DATE DATE,
    TO_DATE DATE,
    INDEX(EMP_NO),
    CONSTRAINT FK_EMP_TITLES FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
    CONSTRAINT PK_TITLES PRIMARY KEY(EMP_NO, TITLE, FROM_DATE)
);